#!/bin/bash

THISDIR=$(cd $(dirname $0) ; pwd)
INSTALLDIR=$(cd $(dirname $0)/.. ; pwd)
PATH=~/noderoot/bin:$PATH

case $1 in 

    install)
	cd $INSTALLDIR
	npm install $THISDIR
	npm install -g forever
        ;;

    stop)
	cd $INSTALLDIR
	forever stop node_modules/marmalade/marmalade.js
        ;;

    start)
	cd $INSTALLDIR
	forever start node_modules/marmalade/marmalade.js 
        ;;

    restart)
        bash $0 install
        bash $0 stop
        bash $0 start
        ;;
esac

# End of install
